// Type stub for src/step.js — the js_of_ocaml output, generated by build.sh
// and excluded by .gitignore. Without this the dynamic import in main.ts does
// not type-check before the first build.
//
// The bundle is a self-executing OCaml program with no exports; importing it
// for its side effects IS the whole interface. Callable exports would need
// js_of_ocaml's Js.export, which is untested here (see README).
export {}
