// GENERATED by tools/gen-cluster-vocab.ts - do not edit by hand.
//
// Refresh:  bun tools/gen-cluster-vocab.ts
//
// COMPLETION ONLY. These add members to three empty interfaces in the SDK so
// `keyof` yields a union of objects that exist. Deleting this file loses
// suggestions and changes nothing about what type-checks - ApiPath,
// WorkloadName and LabelSelector each keep their shape constraint on their own.
//
// A stale entry suggests an object that is gone. That is annoying and never
// wrong, which is why this is refreshed by hand rather than by the build.

declare module '@apsis-io/perseid/perseid' {
  /** Deployment paths - what `observe.get` and `scale` address. */
  interface KnownWorkloadPaths {
    "/apis/apps/v1/namespaces/apsis/deployments/apogeos": true
    "/apis/apps/v1/namespaces/apsis/deployments/radiant": true
    "/apis/apps/v1/namespaces/default/deployments/api": true
    "/apis/apps/v1/namespaces/default/deployments/cluster-state-api": true
    "/apis/apps/v1/namespaces/default/deployments/demo": true
    "/apis/apps/v1/namespaces/default/deployments/magic-echo-c": true
    "/apis/apps/v1/namespaces/default/deployments/magic-echo-go": true
    "/apis/apps/v1/namespaces/default/deployments/magic-echo-quic": true
    "/apis/apps/v1/namespaces/default/deployments/magic-echo-tailnet": true
    "/apis/apps/v1/namespaces/default/deployments/magic-echo-ts": true
    "/apis/apps/v1/namespaces/ix-bench/deployments/ix-bench-redis": true
    "/apis/apps/v1/namespaces/ix-bench/deployments/stz-test": true
    "/apis/apps/v1/namespaces/kube-system/deployments/constellation-operator": true
    "/apis/apps/v1/namespaces/kube-system/deployments/coredns": true
    "/apis/apps/v1/namespaces/local-path-storage/deployments/local-path-provisioner": true
    "/apis/apps/v1/namespaces/nginx-demo/deployments/nginx-whoami": true
    "/apis/apps/v1/namespaces/w8s-workloads/deployments/w8s-api": true
  }

  /** Deployment names - what `Replicas`/`replicasNe` address, resolved in the grant's namespace. */
  interface KnownWorkloadNames {
    "api": true
    "apogeos": true
    "cluster-state-api": true
    "constellation-operator": true
    "coredns": true
    "demo": true
    "ix-bench-redis": true
    "local-path-provisioner": true
    "magic-echo-c": true
    "magic-echo-go": true
    "magic-echo-quic": true
    "magic-echo-tailnet": true
    "magic-echo-ts": true
    "nginx-whoami": true
    "radiant": true
    "stz-test": true
    "w8s-api": true
  }

  /** Label selectors in use - what `ListPods`/`countNe` address. */
  interface KnownSelectors {
    "app=api": true
    "app=apogeos": true
    "app=cluster-state-api": true
    "app=ix-bench-redis": true
    "app=local-path-provisioner": true
    "app=magic-echo-c": true
    "app=magic-echo-go": true
    "app=magic-echo-quic": true
    "app=magic-echo-tailnet": true
    "app=radiant": true
    "app=stz-test": true
  }

  /** Namespaces that exist - the argument of `path.ns(...)`. */
  interface KnownNamespaces {
    "apsis": true
    "default": true
    "ix-bench": true
    "kube-system": true
    "local-path-storage": true
    "nginx-demo": true
    "w8s-workloads": true
  }

  /** Pod names - the argument of `path.ns(...).pods(...)`. */
  interface KnownPodNames {
    "api-7459df5cc5-c9gkx": true
    "api-7459df5cc5-ngq2n": true
    "api-7459df5cc5-sfkbl": true
    "apogeos-7dc9f46f97-n2gn6": true
    "cluster-state-api-6d5f4f7699-6qk2r": true
    "constellation-agent-nsrqg": true
    "constellation-operator-564b87b8cc-9z7w2": true
    "coredns-64d7bf789d-g4j59": true
    "coredns-64d7bf789d-m2zg4": true
    "ix-bench-redis-7d676cb95c-pmr8n": true
    "kube-apiserver-engifire": true
    "kube-controller-manager-engifire": true
    "kube-postgres-engifire": true
    "kube-scheduler-engifire": true
    "local-path-provisioner-fc9dd5f44-7z4nd": true
    "magic-echo-c-79c78b7b67-qddxm": true
    "magic-echo-go-5c96d5f86d-wdkxx": true
    "magic-echo-quic-64f76746f4-fgzcn": true
    "magic-echo-tailnet-6448fffb4-l5v8n": true
    "perseid-scaler-default": true
    "perseid-scaler-v4": true
    "radiant-85dc6788d8-hk48g": true
    "stz-test-7997f8b8bf-vldzq": true
  }
}

export {}
